version: "3"
services:
  mysql-standalone:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  app:
    image: docker-demo
    build: .
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysql-standalone

volumes:
  db:
